name: "项目推荐"
description: "推荐或自荐一个开源项目"
body:
  - type: input
    id: name
    attributes:
      label: "项目名"
      placeholder: "owner/repo"
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: "简介（一句话）"
    validations:
      required: true
  - type: input
    id: license
    attributes:
      label: "许可证（可选）"
      placeholder: "MIT / Apache-2.0 / ..."
